apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-manager-ingress
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - project-manager.jannekeipert.de
      secretName: multi-domain-cert
  rules:
    - host: project-manager.jannekeipert.de
      http:
        paths:
          - backend:
              service:
                name: project-fetcher
                port:
                  number: 8080
            path: /api
            pathType: Prefix
